### ISSUE TITLE
Why var?

### ISSUE THREAD

**Issue by jsonberry** [arc-repos/arc-functions#2]
Just curious about code style, any particular reason why you've used `var` and no `let` or `const`?

Edit: found some `let` usage in `/index.js` ;)

**Comment by brianleroux** [comment]
Haha! Ya I flirted with all of them. I should write a longer form explanation of my js coding approach. I subset. To focus. I subeset on the most boring code arguably possible. 

Everyone is familiar with `var` for assignment and all it's foibles (which can be useful in some circumstances). Given how boring `var` is there's nothing left to think about. (Except the utility of what I'm trying to achieve with the code I am writing.)

I could entertain `const` and `let` and probably will again. But they add a parse and eval step between myself and the thing I'm trying to get done which is unnecessary noise which wastes my time. I'll take any wetware optimizations I can get!
