### ISSUE TITLE
`arc.http.helpers.static` doesn't return the correct URL for Architect 5.5

### ISSUE THREAD

**Issue by mikemaccana** [arc-repos/arc-functions#27]
**Describe the bug**

Using @architect/functions 2.0.7,  `arc.http.helpers.static` doesn't return the correct dir for Architect 5.5

    `<script src="${static('/js/record-events.js')}"></script>`

when using Architect 5.0.x, correctly return: 

http://localhost:3333/js/record-events.js

However when using Architect 5.5.x:

`static` **should** return http://localhost:3333/_static/js/record-events.js (which is where the file now lives)

But instead it returns

http://localhost:3333/js/record-events.js

Which 404s.

**Comment by brianleroux** [comment]
oh! good call. I wonder… you still might want the s3 url behavior in some cases. maybe we add `arc.http.helpers._static` for the _static URLs ?

**Comment by mikemaccana** [comment]
Hrm a static and a _static seems a bit obscure. Maybe something more explicit if both are needed?

**Comment by brianleroux** [comment]
yeah…its weird! what would u suggest ?

**Comment by mikemaccana** [comment]
OK so I've read https://github.com/arc-repos/architect/blob/master/changelog.md and the updated https://arc.codes/guides/static-assets and I'm still not totally clear. 

I gather:

 - We can access blobs in S3 buckets directly using _static (new in Arc 5.5)
 - We can access S3 through lambda (which is what Arc 5.0 did)

Is that correct?

In what circumstances would we need the older behavior? 

The changelog should also have advice on what to change during the upgrade for static assets to keep working. Maybe we need to move files, maybe we need to call `static()` differently, I'm not sure.

**Comment by mikemaccana** [comment]
Hey @brianleroux I'm a little stuck on this one (trying to update `arc-example-ws` so it works on current code).

I appreciate the detailed answer, but I'm getting lost here. It seems like a really simple problem. https://arc.codes/guides/static-assets does not help as it is out of date:

 - I am on the sandbox.
 - I have a client side JS file
 - `let clientSideJS = static('/index.mjs')` returns a broken URL `/index.mjs`
 - `let clientSideJS = '/_static/index.mjs'` works fine,

**What is the correct way to refer to a JS file in `public` so that it will work on sandbox, staging, production, etc?**

I can update the docs accordingly if you need.

**Comment by mikemaccana** [comment]
Still occurs on @architect/architect 5.6.3 + @architect/functions 3.0.1

**Comment by brianleroux** [comment]
on a flight today but have this in my queue!

**Comment by brianleroux** [comment]
should be fixed in latest!
