### ISSUE TITLE
Adding a status to response causing an error

### ISSUE THREAD

**Issue by hicksy** [arc-repos/arc-functions#3]
Great project - I've hit an issue that I'm struggling to resolve - I'm having difficulty setting the `status` param of the response function. 

```
res({
      status: 403,
      json: { msg: 'unauthorised'}
    })
```
This results in a JSON parse error `SyntaxError: Unexpected token o in JSON at position 1` in my terminal 

If I remove the status param, the response correctly returns the JSON payload `{msg: "unauthorised"}` when the request object doesn't include a valid authorization header.

I'm not sure if I've misunderstood the documentation, or if there is fact an issue, my full route below. 

Thanks!

```
var arc = require('@architect/functions')

function route(req, res) {
  console.log(JSON.stringify(req, null, 2))
 
  res({
    json: {hello:'world'}
  });
  
}

function check(req, res, next) {

  if (req.headers.authorization == 'xxxx') {
    next()
  }
  else {
    res({
      status: 403,
      json: { msg: 'unauthorised'}
    })
  }
}



exports.handler = arc.json.post(check, route)
```

**Comment by brianleroux** [comment]
weird! I'll investigate today --- thx for the heads up

**Comment by brianleroux** [comment]
quick update: just reproduced this and looking into a fix!

**Comment by brianleroux** [comment]
Update 2: that was fun. I have a fix! If you are feeling adventurous you could apply it manually.

You'll need to update the *Integration Response* body mapping template for `application/json` for the `403`, `404` and `500` statuses. 

```vtl
#set($raw = $input.path('$.errorMessage'))
#set($len = $input.path('$.errorMessage').length() - 1)
#set($body = $raw.substring(25, $len))
$body
```

The long story short API Gateway `utils.parseJson` returns values that do not stringify back to JSON. So we have the above hack which substrings the JSON payload out. It is not pretty _but it works_. I'll try to land this back into `arc-workflows` as soon as I can.

https://6nfxj2b5v4.execute-api.us-east-1.amazonaws.com/staging/api

**Comment by brianleroux** [comment]
Ok got to it! Fixed in `architect/workflows@1.1.15`. If you delete the offending routes in API Gateway and then recreate them with `npm run create` they should work as expected. Let me know how you go and I'll keep the bug open 👍

**Comment by hicksy** [comment]
Nice one (sorry for slow reply) - upgraded to `architect/workflows@1.1.15` and working great 👍

**Comment by brianleroux** [comment]
awesome!! thx for helping work thru it 💯
