### ISSUE TITLE
async @events handler not invoked properly in sandbox?

### ISSUE THREAD

**Issue by alexbepple** [arc-repos/arc-functions#34]
The guide at https://arc.codes/guides/background-tasks shows a callback-style @events handler. But as async @http handlers are supported, I assumed the callback example was just legacy. So I use an async @events handler:

```javascript
export const handler = arc.events.subscribe(async record => {
  console.log(record)
  await doSth(record)
})
```

This works fine when deployed on AWS. However, today I noticed a problem with the sandbox when automating local system tests. The mocha tests would not terminate properly because a subprocess for `src/sandbox/events/_subprocess.js` remained. Turns out, this piece of code never gets called: https://github.com/arc-repos/architect/blob/master/src/sandbox/events/_subprocess.js#L16-L20
I am guessing the invocation with `(event, context, cb)` is off.

Are async handlers not fully supported or is this a bug in the sandbox?

**Comment by brianleroux** [comment]
We've never supported this and it shouldn't have worked at all! But its a good idea to add. =)

Published in `@architect/functions@3.0.5` thx for reporting @alexbepple

**Comment by brianleroux** [comment]
(for the curious the impl https://github.com/arc-repos/arc-functions/blob/master/src/events/_subscribe.js#L15)

**Comment by brianleroux** [comment]
(also whipped up an example for those interested; it works locally and deployed https://github.com/brianleroux/arc-example-sns)
