### ISSUE TITLE
req._static S3 bucket URL is (sometimes) incorrect

### ISSUE THREAD

**Issue by sentience** [arc-repos/arc-functions#5]
My project specifies the following buckets:

```
@static
staging cultureamp-facewall-staging
production cultureamp-facewall-production
```

In staging, `req._static('main.js')` produces this URL:

https://s3.amazonaws.com/cultureamp-facewall-staging/main.js

If you click this, you'll see S3 responds with a `PermanentRedirect` XML response, which indicates the correct URL is:

https://cultureamp-facewall-staging.s3.amazonaws.com/main.js

**Comment by ryanblock** [comment]
Hey @sentience, check out `1.9.3`, I think that should resolve this problem for good! 🤞

**Comment by sentience** [comment]
Thanks, @ryanblock!
