### ISSUE TITLE
JSON response with status field works on sandbox, malformed on AWS

### ISSUE THREAD

**Issue by sentience** [arc-repos/arc-functions#7]
This `@json` route handler returns a 404 error with a JSON response body:

```js
let arc = require("@architect/functions");

function route(req, res) {
    res({
      json: { error: "Record not found" },
      status: 404,
    });
}

exports.handler = arc.json.get(route);
```

This works fine with `npx sandbox`, but once deployed to AWS, the response is malformed:

```
HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 29
Connection: close
Date: Tue, 09 Oct 2018 01:51:46 GMT
x-amzn-RequestId: e0eb42f5-cb65-11e8-8151-61272b94e470
Set-Cookie: 
x-amz-apigw-id: OeZz0GEwPHcF93g=
Location: {"json":{"error":"Record not found"},"status":404,"cookie":"_idx=Bc_8OuTkTXn2rPpp5-YUpJeT.oZB50nUXMa6f1pobTyvDF4lTciizMUZgRyaY8%2BdmrxI; Max-Age=2327449906161; Path=/; Expires=Sat, 03 Oct 2043 01:51:46 GMT; HttpOnly; Secure; SameSite=Lax","statusCode":404}
X-Amzn-Trace-Id: Root=1-5bbc09b2-077d8ab2d93f18d9ff444633;Sampled=0
X-Cache: Error from cloudfront
Via: 1.1 68807936c056006818525c5da31d108e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: YQWk0k2i71QlZZ0OwGGEIA6IspUf4ajJj6WjwNnzUAvq8kIJ8vqGNw==

ord not found"},"status":404
```

Note the `Location` header value!

**Comment by brianleroux** [comment]
very strange, I just tried to reproduce this and was not able to [1]

(It did populate location with the value of the payload too… which is a funny quirk!)

What version of arc and/or can you share the .arc file?

[1] https://ifs2nst4zj.execute-api.us-east-1.amazonaws.com/staging

**Comment by brianleroux** [comment]
thx again for this! just commented in your other issue and I think we're all resolved for 4.x! pls don't hesitate to reopen (or create a new issue) if you have additional thoughts!
